name: Build
on:
  pull_request: {}
  push:
    branches:
    - main
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: w3c/spec-prod@v2
      with:
        TOOLCHAIN: bikeshed
        SOURCE: isolated-contexts.bs
        DESTINATION: isolated-contexts.html
        GH_PAGES_BRANCH: gh-pages
        BUILD_FAIL_ON: warning
